---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-figs/"
)
```

# ggsidekick

Contains a simple theme for ggplot2, `theme_sleek()`, that loosely resembles nicely themed plots (to my taste) from R base graphics. The theme builds on `ggplot2::theme_light()`. I may add more ggplot helper functions in the future.

Installing:

```{r, eval=FALSE}
# install.packages("devtools")
devtools::install_github("seananderson/ggsidekick")
```

Exciting demo with dataset showing the number of breaks in yarn during weaving for 2 yarn types and 3 tension levels:

```{r, echo=FALSE}
set.seed(1)
```

```{r example, fig.width=5.5, fig.height=3.6, fig.retina=2}
library(ggsidekick)
library(ggplot2)
ggplot(warpbreaks, aes(tension, breaks)) + 
  geom_violin(fill = "grey90", col = NA) +
  geom_jitter(width = 0.1, height = 0, alpha = 0.7) +
  facet_wrap(~wool) + labs(x = "Tension", y = "Breaks") +
  theme_sleek() # ggsidekick magic happens here
```
